### ISSUE TITLE
`tw-install.sh` manual install fails at the very last line on `source src/run_taskserver_at_boot.sh`

### ISSUE THREAD

**Issue by dehidehidehi** [HiveMinds/tw-install#103]
Good afternoon,

`tw-install.sh` manual install fails at the very last line on `source src/run_taskserver_at_boot.sh`.

To make things work I had to manually `cd ./src && source ./run_taskserver_at_boot.sh`.

Cheers,

**Comment by a-t-0** [comment]
Thank you for pointing out this error, and for providing a solution. I have reproduced the bug, applied your solution and pushed to main. I will now look at: #102
